modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "villager_coin"
version = "${version}"
displayName = "Villager Coin"
authors = "Monte_Carlo_Simulations"
description = '''
Adds Villager Coins and trading mechanics to Minecraft.
'''
logoFile = "logo.png"

[[dependencies.villager_coin]]
modId = "neoforge"
type = "required"
versionRange = "[21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.villager_coin]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.villager_coin]]
modId = "architectury"
type = "required"
versionRange = "[18.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "villager_coin.mixins.json"
